tags:
- name: Products API
  description: MEC Products
- name: Orders API
  description: Handle orders on MEC platform
- name: Index

paths:
# [GET] index
  /api/v1/:
    get:
      tags:
      - Index
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] products
  /api/v1/products:
    get:
      tags:
      - Products API
      summary: Get All Products
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] products/:productId
  /api/v1/products/{productId}:
    get:
      tags:
      - Products API
      summary: Find Product By productId
      parameters:
      - name: productId
        in: path
        description: Product Id
        required: true
      responses:
        200:
          description: 'OK'
        400:
          description: 'Product not found'
        500:
          description: 'Server Error'
# [GET] products/hot-deals
  /api/v1/products/hot-deals:
    get:
      tags:
      - Products API
      summary: Get Hot Deals
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
# [GET] orders
  /api/v1/orders:
    post:
      tags:
      - Orders API
      summary: Get All User Orders
      # parameters:
      # - name: productId
      #   in: path
      #   description: Product Id
      #   required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  /api/v1/orders/confirm:
    post:
      tags:
      - Orders API
      summary: Confirm Order
      responses:
        200:
          description: 'OK'
        404:
          description: 'Product not found'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# definitions
# definitions:
#   users:
#     type: object
#     required:
#         - email
#         - password
#     properties:
#       id:
#         description: user Id
#       email:
#         type: string
#         description: user Email
#       password:
#         type: string
#         description: user Password

schemes:
 - http
 - https
